############################################################
# +------------------------------------------------------+ #
# |                 Plugin By Skuller                    | #
# |            https://discord.gg/WwVmxeXEgH             | #
# +------------------------------------------------------+ #
############################################################

# If you receive an error when Rival Run loads,  ensure that:
#  - No tabs are present: YAML only allows spaces
#  - Indents are correct: YAML hierarchy is based entirely on indentation

#<-------------------------------------------------------->#
# Configuration File Starts Here
#<-------------------------------------------------------->#


############################################################
# +------------------------------------------------------+ #
# |             📜 Commands Configuration                | #
# |                 Plugin By Skuller                    | #
# +------------------------------------------------------+ #
############################################################
commands:
  # This command is used to force end the game.
  # This can only be run by administrators.
  #
  # Usable Parameters: Boolean (true / false)
  endGame: true

  # This command is used to pause the game for all the players.
  # This can only be run by administrators.
  #
  # Usable Parameters: Boolean (true / false)
  pauseGame: true

  # This command can be used by players to select their team if they missed the first login event.
  # This command can be run by anyone in the server.
  # You can only run this command before the start of the game.
  #
  # Usable Parameters: Boolean (true / false)
  teamSelect: true

  # This command can be used to leave the team the player is in.
  # This command can be run by anyone in the server.
  # You can only run this command before the start of the game.
  #
  # Usable Parameters: Boolean (true / false)
  teamLeave: true

  # These are a set of developer commands used to debug/ test the plugin.
  # You can mess around with them if you want.
  # You need to be opped to run these commands.
  #
  # Usable Parameters: Boolean (true / false)
  debug: false



############################################################
# +------------------------------------------------------+ #
# |              🧸 GUI Configuration                    | #
# |                Plugin By Skuller                     | #
# +------------------------------------------------------+ #
############################################################
gui:
  # This determines if the fillers in the GUI is enabled or not
  # Change this to false if you don't want fillers (Design)
  #
  # Usable Parameters: Boolean (true / false)
  filler: true

  # Filler Names are the names used for fillers in the GUI
  # Only works if filler is set to true
  #
  # Usable Parameters: String + MiniMessage format
  filler-1-name: ""
  filler-2-name: ""

  # Turn all the plugin GUI's on and off by changing the values here
  # If you change the values here some commands might have severe changes and
  # Some may even get disabled if you set this to false.
  #
  # Usable Parameters: Boolean (true / false)
  test-gui: true



############################################################
# +------------------------------------------------------+ #
# |              ➕ Grace Configuration                  | #
# |                 Plugin By Skuller                    | #
# +------------------------------------------------------+ #
############################################################
grace:
  # This determines if you want to enable a grace period or not
  # Recommended: true
  #
  # Usable Parameters: Boolean (true / false)
  enabled: true

  # This determines the grace period if its enabled.
  # You cannot provide a value below 1 minute. (60 Seconds)
  # You have to enter the value in seconds.
  # Ex: 5 Minutes would be 300 seconds (5 * 60 = 300)
  #
  # Usable Parameters: Integer (Seconds)
  gracePeriod: 300



############################################################
# +------------------------------------------------------+ #
# |              ➕ Teams Configuration                  | #
# |                 Plugin By Skuller                    | #
# +------------------------------------------------------+ #
############################################################
teams:
  # The number of teams that you want.
  # Team is categorized into colors by default so you don't have to give the team a name,
  # Just enter in the number of teams you want in the server.
  #
  # Usable Parameters: Integer (2 to 7)
  list: 3

  # The max number of players you want per team.
  # The min is by default 0 so you don't have to worry about that.
  #
  # Usable Parameters: Integer (2 to 6)
  max: 2

  # This parameter controls if the players in a team can harm each other.
  # Set this to 'true' if you want to enable friendly fire. (teammates can damage each other)
  # Set this to 'false' if you want to disable friendly fire. (teammates cannot damage each other)
  # Recommendation: false
  #
  # Usable Parameters: Boolean (true / false)
  friendlyFire: false

  # This parameter handles team switching.
  # Set this to 'true' if you want players to be able to switch teams mid-game.
  # Set this to 'false' if you don't want players to be able to switch teams mid-game.
  # Recommendation: false
  #
  # Usable Parameters: Boolean (true / false)
  teamSwitching: false

  # This controls the GUI that appears when players first join the game.
  # Set this to 'true' if you want players to get a prompt to select the team
  # Set this to 'false' if you don't want players to get a pop-up tp select the team
  # Recommendation: true
  #
  # Usable Parameters: Boolean (true / false)
  loginGUI: true

  # This controls what the teams are gonna be named
  # There are some already predefined names in the system you cannot edit them.
  # But you may select which one of those name sets you want to use.
  #
  # 0: Default (RED, BLUE, GREEN, YELLOW, AQUA, PURPLE)
  # 1: Passive Mobs (Pig, Cow, Chicken, Sheep, Squid, Axolotl)
  # 2: Hostile Mobs (Zombie, Creeper, Blaze, Piglin, Enderman, Warden)
  # 3: Flowers (Rose, Dandelions, Sunflower, Cornflower, Tulip, Lilly)
  # 4: Blocks (Wood, Stone, Sand, Deepslate, Obsidian, Endstone)
  #
  # Usable Parameters: Integers (Select from the above list)
  teamName: 0





# Plugin Configuration Version
# ⚠️ Do Not Change ⚠️️
# If you change this value there is a high chance for your config file to get reset.
version: 0.1