name: RivalRun
version: '1.0-SNAPSHOT'
main: xyz.skuller.rivalRun.RivalRun
api-version: '1.21'
authors: [ Skuller ]
description: A plugin built for speedrunning minecraft with friends.

commands:
  rivalrun:
    description: Main entry point for all the commands in the plugin.
    aliases:
      - rr
  rrdebug:
    description: Dev command for rival run (just for testing purposes).
